version: '3'

services:

  # *********** Main *************

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file: 
      .env
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - wp_database:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
      # - redis
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always


# ************* Bonus *************

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "20:20"
      - "30000-30009:30000-30009"
    env_file:
      - .env
    volumes:
      - wp_files:/home/hamid/ftp
    networks:
      - inception
    restart: always



  # ************* volumes and networks *************

volumes:
     wp_database: 
       driver: local
       driver_opts:
         type: none
         device: /home/shinra/data/wp_database
         o: bind
     wp_files:
       driver: local
       driver_opts:
         type: none
         device: /home/shinra/data/wp_files
         o: bind

networks:
  inception: {}
