version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file: 
      .env
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - wp_database:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always
# bonus


  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always


volumes:
     wp_database: 
       driver: local
       driver_opts:
         type: none
         device: /home/shinra/data/wp_database
         o: bind
     wp_files:
       driver: local
       driver_opts:
         type: none
         device: /home/shinra/data/wp_files
         o: bind

networks:
  inception: {}
